module.exports = [
  {
    id: 1,
    title: '首页',
    icon: 'icon-home',
    url: '/home',
    parent: null,
    desc: '首页',
    sorts: 0,
    conditions: 1,
  },
  {
    id: 2,
    title: '系统管理',
    icon: 'icon-setting',
    url: '/system',
    parent: null,
    desc: '系统管理目录分支',
    sorts: 1,
    conditions: 1,
  },
  {
    id: 3,
    title: '用户管理',
    icon: 'icon-user',
    url: '/system/useradmin',
    parent: 2,
    desc: '系统管理/用户管理',
    sorts: 0,
    conditions: 1,
  },
  {
    id: 4,
    title: '角色管理',
    icon: 'icon-team',
    url: '/system/roleadmin',
    parent: 2,
    desc: '系统管理/角色管理',
    sorts: 1,
    conditions: 1,
  },
];
